<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\UploadImage;
use App\Form\UploadImageType;
use App\Service\FileUploader;
use App\Repository\UploadImageRepository;
use Symfony\Component\HttpFoundation\Response;

class UploadImageController extends AbstractController {

    /**
     * @Route("/image", name="Liste_Image", methods="GET")
     */
    public function index(UploadImageRepository $UploadImageRepository): Response {
        return $this->render('Image/image_list.html.twig', ['images' => $UploadImageRepository->findAll()]);
        }
        /**
         * @Route("/image/new", name="app_image_new")
         */
        public function new(Request $request)
        {
        $image = new UploadImage;
        $form = $this->createForm(UploadImageType::class, $image);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
        
        // $file stores the uploaded PDF file
        //@var Symfony\Component\HttpFoundation\File\UploadedFile $file 
        $file = $image->getImage();
        $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
        $file->move(
                $this->getParameter('image_directory'), $fileName
        );
        $image->setImage($fileName);
        $file = $this->getDoctrine()->getManager();
        $file->persist($image);
        $file->flush();

        return $this->redirect($this->generateUrl('Liste_Image'));
        }

        return $this->render('Image/new.html.twig', array(
                    'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName() {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}
